apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "minlog.name" . }}
  labels:
    {{- include "minlog.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - envents
  - namespaces
  - nodes
  - pods
  - services
  - deployments
  - daemonsets
  - statefulsets
  - replicasets
  verbs:
  - get
  - list
  - watch
