apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "minlog.name" . }}
  labels:
    {{- include "minlog.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "minlog.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "minlog.serviceAccountName" . }}
    namespace: {{ $.Release.Namespace }}
