deploymentMode: SimpleScalable
loki:
  image:
    registry: null
    repository: crpi-2re4a582sqaza89h.cn-hangzhou.personal.cr.aliyuncs.com/venomous/loki
    tag: 3.4.2
  auth_enabled: false
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  ingester:
    chunk_encoding: snappy
  querier:
    # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
    max_concurrent: 4
  pattern_ingester:
    enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
  storage:
    # aliyun oss settings
    type: s3
    s3:
      s3: oss-cn-beijing.aliyuncs.com
      endpoint: oss-cn-beijing.aliyuncs.com
      region: cn-beijing
      accessKeyId: ""
      secretAccessKey: ""
    bucketNames:
      chunks: minlog-chunks
      admin: minlog-admin
      ruler: minlog-ruler
  podSecurityContext:
    fsGroup: 0
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0

memcached:
  podSecurityContext:
    runAsNonRoot: false
    fsGroup: 0
    runAsGroup: 0
    runAsUser: 0
  image:
    # -- Memcached Docker image repository
    repository: crpi-2re4a582sqaza89h.cn-hangzhou.personal.cr.aliyuncs.com/venomous/memcached
    # -- Memcached Docker image tag
    tag: 1.6.38-alpine

memcachedExporter:
  # -- Whether memcached metrics should be exported
  enabled: false

resultsCache:
  allocatedMemory: 1024
chunksCache:
  allocatedMemory: 2048

read:
  replicas: 2

write:
  replicas: 3 # To ensure data durability with replication

  # either affinity or nodeselector, affinity is better
  # #affinity
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              loki.component: write
          topologyKey: kubernetes.io/hostname
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: loki.component 
            operator: In
            values:
            - write
            - writebackend
  # #nodeSelector
  #nodeSelector:
  #  application/loki.write: true

  # PVC enabled, specify the storageclass and size, even if it is default 
  # The simplest deployment topology, high performance SAN
  # pv(s) must have been created if local storage(name/size/storageClass flowing )
  #persistence:
  #  storageClass: mystorageclass 
  #  size: 2000G

  # hostPath enabled()
  persistence:
    volumeClaimsEnabled: false
    dataVolumehostPath:
      hostPath:
        path: /data/loki/write
        type: DirectoryOrCreate

backend:
  replicas: 2
  # #affinity
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: loki.component
              operator: In
              values:
              - write
              - writebackend
          topologyKey: kubernetes.io/hostname
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: loki.component 
            operator: In
            values:
            - write
            - writebackend
  # hostPath enabled()
  persistence:
    volumeClaimsEnabled: false
    dataVolumehostPath:
      hostPath:
        path: /data/loki/backend
        type: DirectoryOrCreate
sidecar:
  image:
    # -- The Docker registry and image for the k8s sidecar
    repository: crpi-2re4a582sqaza89h.cn-hangzhou.personal.cr.aliyuncs.com/venomous/k8s-sidecar
    # -- Docker image tag
    tag: 1.30.2

    
  # Enable minio for storage
minio:
  enabled: false

gateway:
  service:
    type: NodePort
